### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by Random663** [onoderis/bgc-script#1]
The script doesn't seem to be detecting the process GenshinImpact.exe despite it being opened and fullscreened. I tried to remove the WinWaitActive and pauseloop line but even then, only [numpad -] to spam left click is working, the mbutton left and mbutton right doesn't seem to work in the script. 

Ran as admin on latest AHK version.

**Comment by onoderis** [comment]
You might need to run the game in a borderless window, here is the instruction: https://gaming.stackexchange.com/a/376533
The script disables certain hotheys if it can't detect game's interface on the screen (see `ConfigureBindings()` function).

If borderless window isn't gonna work, I am afraid you have to figure it out on your own because I have stopped playing the game and I don't want to install it again 😅

**Comment by Random663** [comment]
I see, is there a way to remove the detection on the script while retaining the functionality? I'm trying to tweak with the file but can't seem to get it working.

**Comment by onoderis** [comment]
There is a way, just run this block of code once on initialization https://github.com/onoderis/bgc-script/blob/master/better-genshin-controls.ahk#L80

But if you do so, some features will be completely broken (such as expeditions) and other will cause significant inconveniences to your gameplay. For example, you cannot normally do mouse clicks if the bindings are active.
