### ISSUE TITLE
Enable/disable contextual bindings issue

### ISSUE THREAD

**Issue by Ralphiius** [onoderis/bgc-script#4]
Noticed no matter what my bindings for attack spam and loot are always disabled. I can't seem to find a way to have them enabled. 

`094: PixelGetColor,Color,807,1010,"RGB"
095: HpBarFound := (Color = "0x8DC921") || (Color = "0xEF5555") || (Color = "0xEFBF2F")
097: PixelGetColor,ThirdActionItemColor,1626,1029,"RGB" (0.03)
098: FishingActive := ThirdActionItemColor = "0xFFE92C"
100: Toggled := 0
101: if (HpBarFound && !FishingActive)  
108: Hotkey,*~LButton,NormalAutoAttack,Off
109: Hotkey,*RButton,StrongAttack,Off
110: Hotkey,~$*f,Loot,Off
111: }
112: } (0.06)`

**Comment by onoderis** [comment]
Hi, @Ralphiius 
1. Do you run the script with administrator rights?
2. Do you have a second monitor?
3. What is your monitor resolution and game resolution?
4. Please provide a screenshot in lossless quality (for example in .png format) when you expect the bindings to work.

**Comment by Ralphiius** [comment]
1. Yes I do run as administrator. All other features work as described. 
2. I do not. 
3. Monitor resolution is 2560 x 1440. Game is running at 1920 x 1080. 
4. https://imgur.com/qDC9UlU

I believe the actions in question are meant for combat so in open world. Holding F does not work to loot quickly, and not able to just spam left mouse button for attack.

**Comment by onoderis** [comment]
> I believe the actions in question are meant for combat so in open world.

Correct. The script tries to determine state of the game by HP bar, more precisely by a color of a single pixel on the HP bar, and disables hotkeys that can break menus.
In your case that pixel has color 8DCA21 instead of 8DC921 for some reason. Please, share all your graphical settings, it may be the cause.

You could try to partially fix the problem by changing the line
https://github.com/onoderis/bgc-script/blob/84f8055219a16c2b3f51a46fe7097240bb89e463/better-genshin-controls.ahk#L95
to
```
    HpBarFound := (Color = "0x8DCA21")
```
It will show is there any other issues besides described one. To test this your HP bar must be green.

Also, ensure that your game window is always on top left corner and the window has no frame.

**Comment by Ralphiius** [comment]
Hmmm top left corner? The game window is center on my setup. It has no frame. 

The fix you presented does work. Thank you. 

My settings.
https://imgur.com/a/ih1rJox

**Comment by onoderis** [comment]
> Hmmm top left corner? The game window is center on my setup. It has no frame.

My bad, it is not necessary for window to be in the top left corner.

I haven't found the reason why pixel color differs on my game client and on yours, it's not the graphics settings and I'm currently out of ideas. But I've change the script so it should work for you without any additional changes - ab009513703207d53f559c34d9395798c99059a8

Do you play with 1920x1080 resolution because the script doesn't support your screen resolution? Or you just comfortable to play this way?

**Comment by Ralphiius** [comment]
Thank you for the quick fix! 

When the game first loaded it was this resolution and I didn't bother to change it. It's now normal for me. Also nice to tab between sites and game. 

Thank you again!
